### ISSUE TITLE
Rekono Settings Desktop would just display blank when defect-dojo IP url is changed.

### ISSUE THREAD

**Issue by dennisarriola** [pablosnt/rekono#276]
**Describe the bug**
I am using Kali Linux in Hyper-V, the hyper-v IP is not static so it will be changed every time. I updated the defect-dojo configuration settings to allow the assigned IP of the host. However, whenever IP is changed, the Rekono Setting View on desktop just display blank

**To Reproduce**
1. Go to Settings
2. See error, it only displays blank

**Expected behavior**
Should display the current settings so that defect-dojo URL can be changed.

**Screenshots**
![Screenshot from 2024-03-18 21-49-15](https://github.com/pablosnt/rekono/assets/54200801/c3f1e943-98bb-4a61-813e-013aa0f28fe5)

**Environment**
 - OS: Kali Linux
 - Browser N/A
 - Version N/A

**Installation method**
- [ ] Docker
- [ ] DEB package
- [ ] From Source

**Additional context**

**Comment by dennisarriola** [comment]
The log says " [Telegram Bot] Error during Telegram bot name request" but I did not set up Telegram account, I only use defect-dojo and i noticed this everytime the IP is changed~
Thank you.

**Comment by pablosnt** [comment]
Hi @dennisarriola,

Don't worry about the Telegram bot log message. Telegram and Defect-Dojo settings are handled in the same database model and API, so when you update any of these data, it tries to get the Telegram bot name and it fails. It's an expected and handled error, so don't worry about it.

Regarding Defect-Dojo, your integration is already working? I think the blank page's reason is that your Defect-Dojo configuration is not right, so the page turns blank while it's waiting for the Defect-Dojo connection check, for which Rekono has a long timeout. Does it make sense?

I know that it's not a good UX and it will be fixed in the next version

Thank you for reporting

**Comment by pablosnt** [comment]
Hi @dennisarriola, if it's related to the UX, this is something that I will include as part of the issue https://github.com/pablosnt/rekono/issues/217. I will close this one, anyway, let me know if I can help you in something else. Thanks!
