### ISSUE TITLE
Export Findings

### ISSUE THREAD

**Issue by SanketBaraiya** [pablosnt/rekono#314]
Is there any way to export all the findings of particular domain

**Comment by pablosnt** [comment]
Hello,

You can use the API Rest to get the findings from an automated script or something similar, and you can apply whatever filter you need, as the API is very flexible. Note that you can use the https://github.com/pablosnt/rekono-cli to call the API from your terminal or a Python script.

I know this is not the perfect solution, which is why version 2.0.0 of Rekono will include findings exporting features to JSON, XML, and PDF files, from the UI. I expect to release the new 2.0.0 version during this year. I'm happy to see it will be useful.

**Comment by SanketBaraiya** [comment]
Thanks for your response. Will surely try it with API for now and wait for the new release. Thanks @pablosnt

**Comment by pablosnt** [comment]
You are welcome! I will close the issue for now :)
