### ISSUE TITLE
Error in nginx using while starting the app using docker

### ISSUE THREAD

**Issue by SanketBaraiya** [pablosnt/rekono#315]
I am not able to access the application when I build it and up it using docker. I think its something related to nginx config. This is the error I am facing currently.

![image](https://github.com/pablosnt/rekono/assets/56958135/7b4c96ea-5ad7-4b4a-908f-29a07a75d553)

This error keeps repeating.

**Comment by SanketBaraiya** [comment]
Hi @pablosnt any solution to this?

**Comment by pablosnt** [comment]
Hi @SanketBaraiya yes, this is a common error and has an easy solution. There is a section in the [FAQ](https://github.com/pablosnt/rekono/wiki/FAQ#permission-error-during-nginx-execution) where it's explained both the problem and the solution.

Let me know if this solves the problem, I hope so

**Comment by SanketBaraiya** [comment]
Hi @pablosnt , Thanks for your response. I followed the steps adn verified the permission changes but I am still encountering same error here are the screenshots if that helps. Thanks

![image](https://github.com/pablosnt/rekono/assets/56958135/3ea19734-0035-4464-9b57-ff4f65a059b5)

**Comment by pablosnt** [comment]
Hi,

Note that `/etc/nginx/tls` is not found as the path is included in the error from the Nginx running in a container. That path is mapped to your `docker/nginx/tls` path.

Maybe I'm wrong but did you clone the repo as root? I think it's the usual case and I would propose to clone it with a non-root user. I don't fully understand why, but when the repo is cloned as root, that folder belongs to root and then is not reachable by the container through the mapped. I will research the problem deeper for the next version because it's a common issue.

**Comment by pablosnt** [comment]
I'm closing this issue for now. Please, feel free to reopen or comment if you didn't solve the problem. Thank you!
